name: bukadonasi
description: Aplikasi Buka Donasi

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  akun:
    path: akun
  auth:
    path: auth
  berita:
    path: berita
  core:
    path: core
  donasi:
    path: donasi
  galang:
    path: galang
  home:
    path: home
  notifikasi:
    path: notifikasi

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  # ICONS
