name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  akun:
    path: ../akun
  auth:
    path: ../auth
  berita:
    path: ../berita
  donasi:
    path: ../donasi
  galang:
    path: ../galang
  home:
    path: ../home
  notifikasi:
    path: ../notifikasi

  another_flushbar: ^1.10.28
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  convex_bottom_bar: ^3.0.0
  dartz: ^0.10.1
  device_apps: ^2.2.0
  equatable: ^2.0.3
  extended_masked_text: ^2.3.1
  flutter_bloc: ^8.0.1
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_html: ^2.2.1
  form_field_validator: ^1.1.0
  google_sign_in: ^5.2.1
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  loading_animation_widget: ^1.1.0+3
  percent_indicator: ^3.4.0
  pin_code_fields: ^7.3.0
  rxdart: ^0.27.3
  share_plus: ^3.0.4
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  stream_transform: ^2.0.0
  url_launcher: ^6.0.18

dependency_overrides:
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
